spring:
  application:
    name: explore-mybp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

server:
  port: 9002


# Logger Config
logging:
  level:
    com.baomidou.mybatisplus: debug

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl