spring:
  application:
    name: explore-mybp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      #连接池配置
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-wait: 10s


server:
  port: 9002


# Logger Config
logging:
  level:
    self.joy.common: debug

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl